//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.5.1
//     from Assets/InputActions/PlayerInputActions.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @PlayerInputActions: IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @PlayerInputActions()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""PlayerInputActions"",
    ""maps"": [
        {
            ""name"": ""Player action map"",
            ""id"": ""9e8c5a99-be8d-43b5-9699-f2cf0c5b7e92"",
            ""actions"": [
                {
                    ""name"": ""Move"",
                    ""type"": ""Value"",
                    ""id"": ""7ac34ad1-c0f0-4008-9cd3-2eee044ed099"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""055346a7-2d94-4ed5-aa4d-36b1e074133d"",
                    ""path"": ""<AndroidJoystick>/stick"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // Player action map
        m_Playeractionmap = asset.FindActionMap("Player action map", throwIfNotFound: true);
        m_Playeractionmap_Move = m_Playeractionmap.FindAction("Move", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }

    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }

    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // Player action map
    private readonly InputActionMap m_Playeractionmap;
    private List<IPlayeractionmapActions> m_PlayeractionmapActionsCallbackInterfaces = new List<IPlayeractionmapActions>();
    private readonly InputAction m_Playeractionmap_Move;
    public struct PlayeractionmapActions
    {
        private @PlayerInputActions m_Wrapper;
        public PlayeractionmapActions(@PlayerInputActions wrapper) { m_Wrapper = wrapper; }
        public InputAction @Move => m_Wrapper.m_Playeractionmap_Move;
        public InputActionMap Get() { return m_Wrapper.m_Playeractionmap; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(PlayeractionmapActions set) { return set.Get(); }
        public void AddCallbacks(IPlayeractionmapActions instance)
        {
            if (instance == null || m_Wrapper.m_PlayeractionmapActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_PlayeractionmapActionsCallbackInterfaces.Add(instance);
            @Move.started += instance.OnMove;
            @Move.performed += instance.OnMove;
            @Move.canceled += instance.OnMove;
        }

        private void UnregisterCallbacks(IPlayeractionmapActions instance)
        {
            @Move.started -= instance.OnMove;
            @Move.performed -= instance.OnMove;
            @Move.canceled -= instance.OnMove;
        }

        public void RemoveCallbacks(IPlayeractionmapActions instance)
        {
            if (m_Wrapper.m_PlayeractionmapActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(IPlayeractionmapActions instance)
        {
            foreach (var item in m_Wrapper.m_PlayeractionmapActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_PlayeractionmapActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public PlayeractionmapActions @Playeractionmap => new PlayeractionmapActions(this);
    public interface IPlayeractionmapActions
    {
        void OnMove(InputAction.CallbackContext context);
    }
}
